server:
  forward-headers-strategy: native
  port: 8080
  ssl:
    bundle: "local-cert"
    enabled: true

spring:
  application:
    name: easyplan
  config:
    import:
      - optional:file:.env[.properties]
  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
  datasource:
    url: ${JDBC_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_Sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 5000ms
  ssl:
    bundle:
      pem:
        local-cert:
          keystore:
            certificate: ${SSL_CERT}
            private-key: ${SSL_KEY}
jwt:
  secret: ${JWT_SECRET}
  
logging:
  level:
    org:
      springframework:
        security: DEBUG
        cache: trace